apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-marketplace
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: movies-marketplace
  template:
    metadata: 
      labels: 
        app: movies-marketplace
    spec:
      containers:
      - name: movies-marketplace
        image: 530364773324.dkr.ecr.eu-west-2.amazonaws.com/paulappz/movies-marketplace:30b71adf418cb38bdb6cdb3c8d75ee205430683a
        ports:
        - containerPort: 80