apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-loader
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: movies-loader
  template:
    metadata: 
      labels: 
        app: movies-loader
    spec:
      containers:
      - name: movies-loader
        image: 530364773324.dkr.ecr.eu-west-2.amazonaws.com/paulappz/movies-loader:996acd60b9dd93bf6a67e7bf17d54103c43706bb
        env:
        - name: AWS_REGION
          value: REGION
        - name: SQS_URL
          value: https://sqs.eu-west-2.amazonaws.com/530364773324/movies_to_parse_sandbox
        periodSeconds: 20
        failureThreshold: 20