apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-parser
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: movies-parser
  template:
    metadata: 
      labels: 
        app: movies-parser
    spec:
      containers:
      - name: movies-parser
        image: 530364773324.dkr.ecr.eu-west-2.amazonaws.com/paulappz/movies-parser:e2606f20ec69afb8dda1b42e0be92ff791cf06cf
        env:
        - name: AWS_REGION
          value: REGION
        - name: SQS_URL
          value: https://sqs.eu-west-2.amazonaws.com/530364773324/movies_to_parse_sandbox
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-access
              key: database
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-access
              key: uri
        startupProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 1