version: "3.3"

services:
  movies-loader:
    image: 530364773324.dkr.ecr.eu-west-2.amazonaws.com/paulappz/movies-loader:preprod
    environment:
      - AWS_REGION=SQS REGION
      - SQS_URL=https://sqs.eu-west-2.amazonaws.com/530364773324/movies_to_parse_staging
  
  movies-parser:
    image: 530364773324.dkr.ecr.eu-west-2.amazonaws.com/paulappz/movies-parser:preprod
    environment:
      - AWS_REGION=SQS REGION
      - SQS_URL=https://sqs.eu-west-2.amazonaws.com/530364773324/movies_to_parse_staging
      - MONGO_URI=mongodb://root:root@mongodb/watchlist?retryWrites=true&w=majority&poolSize=1
      - MONGO_DATABASE=watchlist
    depends_on:
      - mongodb
  
  movies-store:
    image: 530364773324.dkr.ecr.eu-west-2.amazonaws.com/paulappz/movies-store:preprod
    environment:
      - MONGO_URI=mongodb://root:root@mongodb/watchlist?retryWrites=true&w=majority&poolSize=1
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  movies-marketplace:
    image: 530364773324.dkr.ecr.eu-west-2.amazonaws.com/paulappz/movies-marketplace:preprod
    ports:
      - 80:80

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=root
      - MONGODB_DATABASE=watchlist
